#!/bin/bash
# Domino 10 environment
bjam=/data/libs_external/boost/boost_1_61_0/boost.build/bin/bjam

# Domino 9 environment
#export BOOST_ROOT=/opt/boost/boost_1_61_0
#bjam=${BOOST_ROOT}/bjam
prjcfg=release
application=ssotoken

cd lnx64

echo "Cleaning..."
echo $bjam --clean toolset=gcc $prjcfg
$bjam --clean toolset=gcc $prjcfg

echo "Building new..."
echo $bjam --toolset=gcc $prjcfg
$bjam -d +1 --toolset=gcc $prjcfg
